### ISSUE TITLE
Augmenter la fiabilité de l'import de l'infrastructure SIPH

### ISSUE THREAD

**Issue by skajie** [DGEXSolutions/osrd#1917]
## User

Study officer / Manager / Other

## Description

The already imported SIPH infrastructure has some anomalies. This US will allow us to refine this as much as possible

## Goal

Get a more complete SIPH infrastructure

## Acceptance criteria

- [ ] Criteria 1 : List SIPH import errors
- [ ] Criteria 2 : Add logs for objects traceability
- [ ] Criteria 3 : The SIPH infra is usable by OSRD

## Story points

5

## Definition of ready

- [ ] The user story is well defined
- [ ] Acceptance criterias are defined
- [ ] The individual responsible for validating the user story is assigned
- [ ] The team should understand how to demonstrate the features
- [ ] Does not depend on an missing feature
- [ ] Negociable with the implementation team
- [ ] Valuable to the end users
- [ ] Estimable by the implementation team
- [ ] As small as it can be
- [ ] Testable by the implementation team

## Definition of done

- [ ] Acceptance criteria are met
- [ ] Automated tests are written against acceptance criteria
- [ ] Project deployed to the testing environment
- [ ] Story ok-ed by Product Owner
- [ ] Documentation updated

**Comment by axrolld** [comment]
Got splitted into :
- #2034 
- https://github.com/DGEXSolutions/import-siph/issues/34
- https://github.com/DGEXSolutions/import-siph/issues/35
- https://github.com/DGEXSolutions/import-siph/issues/37
